import { Injectable } from '@angular/core';

export interface Reward {
  pk: number;
  name: string;
  points: number;
  display_img_url: string;
  quantity: number | null;
  valid_until: string;
  low_quantity: number | null;
  category: string | null;
}

@Injectable({ providedIn: 'root' })
export class Data {
  getRewards(): Reward[] {
    const rewards = [
    {
      pk: 1,
      name: 'Café Coffee Day',
      points: 150,
      display_img_url: 'https://upload.wikimedia.org/wikipedia/en/4/48/Caf%C3%A9_Coffee_Day.svg',
      quantity: 14,
      valid_until: '2025-12-31',
      low_quantity: 10,
      category: 'Food'
    },
    {
      pk: 2,
      name: 'KFC',
      points: 2500,
      display_img_url: 'https://upload.wikimedia.org/wikipedia/sco/b/bf/KFC_logo.svg',
      quantity: 2,
      valid_until: '2025-11-30',
      low_quantity: 5,
      category: 'Food',
    },
    {
      pk: 3,
      name: 'Subway',
      points: 800,
      display_img_url: 'https://upload.wikimedia.org/wikipedia/commons/5/5c/Subway_2016_logo.svg',
      quantity: 0,
      valid_until: '2025-11-06',
      low_quantity: 5,
      category: 'Food',
    },
    {
      pk: 4,
      name: `McDonald's`,
      points: 800,
      display_img_url: `https://upload.wikimedia.org/wikipedia/commons/3/36/McDonald%27s_Golden_Arches.svg`,
      quantity: 0,
      valid_until: '2025-11-30',
      low_quantity: 5,
      category: 'Food',
    },
    {
      pk: 5,
      name: `Burger King`,
      points: 1505,
      display_img_url: `https://upload.wikimedia.org/wikipedia/commons/c/cc/Burger_King_2020.svg`,
      quantity: 100,
      valid_until: '2025-12-30',
      low_quantity: 5,
      category: 'Food',
    },
    {
      pk: 6,
      name: `Pepsi`,
      points: 180,
      display_img_url: `https://upload.wikimedia.org/wikipedia/commons/6/68/Pepsi_2023.svg`,
      quantity: 30,
      valid_until: '2025-12-30',
      low_quantity: 8,
      category: 'Food',
    },
    {
    pk: 7,
    name: 'Amazon',
    points: 1000,
    display_img_url: 'https://upload.wikimedia.org/wikipedia/commons/a/a9/Amazon_logo.svg',
    quantity: 10,
    valid_until: '2024-12-31',
    low_quantity: 5,
    category: 'e-Voucher',
  },
  {
    pk: 8,
    name: 'Flipkart',
    points: 850,
    display_img_url: 'https://upload.wikimedia.org/wikipedia/commons/1/13/Flipkart_logo.svg',
    quantity: 6,
    valid_until: '2024-12-15',
    low_quantity: 4,
    category: 'e-Voucher',
  },
  {
    pk: 9,
    name: 'Myntra',
    points: 750,
    display_img_url: 'https://upload.wikimedia.org/wikipedia/commons/0/0d/Myntra_Logo.png',
    quantity: 15,
    valid_until: '2024-11-30',
    low_quantity: 3,
    category: 'e-Voucher',
  },
  {
    pk: 10,
    name: 'eBay',
    points: 700,
    display_img_url: 'https://upload.wikimedia.org/wikipedia/commons/1/1b/EBay_logo.svg',
    quantity: 9,
    valid_until: '2024-12-10',
    low_quantity: 6,
    category: 'e-Voucher',
  },
  {
    pk: 11,
    name: 'AliExpress',
    points: 650,
    display_img_url: 'https://upload.wikimedia.org/wikipedia/commons/2/28/AliExpress_logo.svg',
    quantity: 3,
    valid_until: '2025-01-15',
    low_quantity: 5,
    category: 'e-Voucher',
  },
  {
    pk: 12,
    name: 'Snapdeal',
    points: 600,
    display_img_url: 'https://upload.wikimedia.org/wikipedia/commons/4/4d/Snapdeal_logo.svg',
    quantity: 30,
    valid_until: '2024-12-05',
    low_quantity: 4,
    category: 'e-Voucher',
  },
  {
    pk: 13,
    name: 'Ajio',
    points: 780,
    display_img_url: 'https://upload.wikimedia.org/wikipedia/commons/8/8d/Ajio_logo.png',
    quantity: 4,
    valid_until: '2024-11-25',
    low_quantity: 3,
    category: 'e-Voucher',
  },
  {
    pk: 14,
    name: 'Nike',
    points: 950,
    display_img_url: 'https://upload.wikimedia.org/wikipedia/commons/a/a6/Logo_NIKE.svg',
    quantity: 20,
    valid_until: '2024-12-31',
    low_quantity: 5,
    category: 'Fashion & Retail',
  },
  {
    pk: 15,
    name: 'Adidas',
    points: 900,
    display_img_url: 'https://upload.wikimedia.org/wikipedia/commons/2/20/Adidas_Logo.svg',
    quantity: 18,
    valid_until: '2025-01-15',
    low_quantity: 4,
    category: 'Fashion & Retail',
  },
  {
    pk: 16,
    name: 'Puma',
    points: 870,
    display_img_url: 'https://upload.wikimedia.org/wikipedia/en/f/fd/Puma_AG.svg',
    quantity: 15,
    valid_until: '2024-12-20',
    low_quantity: 3,
    category: 'Fashion & Retail',
  },
  {
    pk: 17,
    name: "Levi's",
    points: 820,
    display_img_url: 'https://upload.wikimedia.org/wikipedia/commons/7/78/Levis-logo.svg',
    quantity: 25,
    valid_until: '2025-02-10',
    low_quantity: 6,
    category: 'Fashion & Retail',
  },
  {
    pk: 18,
    name: 'Zara',
    points: 880,
    display_img_url: 'https://upload.wikimedia.org/wikipedia/commons/f/fd/Zara_Logo.svg',
    quantity: 30,
    valid_until: '2024-11-30',
    low_quantity: 5,
    category: 'Fashion & Retail',
  },
  {
    pk: 19,
    name: 'H&M',
    points: 860,
    display_img_url: 'https://upload.wikimedia.org/wikipedia/commons/5/53/H%26M-Logo.svg',
    quantity: 22,
    valid_until: '2025-01-05',
    low_quantity: 5,
    category: 'Fashion & Retail',
  },
  {
    pk: 20,
    name: 'Ray-Ban',
    points: 940,
    display_img_url: 'https://upload.wikimedia.org/wikipedia/commons/8/8e/Ray-Ban_logo.svg',
    quantity: 10,
    valid_until: '2025-02-28',
    low_quantity: 2,
    category: 'Fashion & Retail',
  },
  {
    pk: 21,
    name: 'Jade Blue',
    points: 780,
    display_img_url: 'https://upload.wikimedia.org/wikipedia/en/4/4e/Jade_Blue_logo.png',
    quantity: 12,
    valid_until: '2024-12-15',
    low_quantity: 3,
    category: 'Fashion & Retail',
  },
  {
    pk: 22,
    name: 'Gucci',
    points: 1200,
    display_img_url: 'https://upload.wikimedia.org/wikipedia/commons/9/9a/Gucci_logo.svg',
    quantity: 8,
    valid_until: '2025-01-25',
    low_quantity: 2,
    category: 'Fashion & Retail',
  },
  {
    pk: 23,
    name: 'Louis Vuitton',
    points: 1300,
    display_img_url: 'https://upload.wikimedia.org/wikipedia/commons/5/5a/Louis_Vuitton_logo_and_wordmark.svg',
    quantity: 6,
    valid_until: '2025-03-10',
    low_quantity: 2,
    category: 'Fashion & Retail',
  },
  {
    pk: 24,
    name: 'Apple',
    points: 1100,
    display_img_url: 'https://upload.wikimedia.org/wikipedia/commons/f/fa/Apple_logo_black.svg',
    quantity: 15,
    valid_until: '2025-10-29',
    low_quantity: 5,
    category: 'Evergreen',
  },
  {
    pk: 25,
    name: 'Google',
    points: 1080,
    display_img_url: 'https://upload.wikimedia.org/wikipedia/commons/2/2f/Google_2015_logo.svg',
    quantity: 20,
    valid_until: '2025-11-15',
    low_quantity: 4,
    category: 'Evergreen',
  },
  {
    pk: 26,
    name: 'Microsoft',
    points: 1040,
    display_img_url: 'https://upload.wikimedia.org/wikipedia/commons/9/96/Microsoft_logo_%282012%29.svg',
    quantity: 18,
    valid_until: '2025-11-30',
    low_quantity: 4,
    category: 'Evergreen',
  },
  {
    pk: 27,
    name: 'Amazon',
    points: 1000,
    display_img_url: 'https://upload.wikimedia.org/wikipedia/commons/a/a9/Amazon_logo.svg',
    quantity: 25,
    valid_until: '2025-12-15',
    low_quantity: 6,
    category: 'Evergreen',
  },
  {
    pk: 28,
    name: 'Tesla',
    points: 1250,
    display_img_url: 'https://upload.wikimedia.org/wikipedia/commons/b/bd/Tesla_Motors.svg',
    quantity: 10,
    valid_until: '2025-12-31',
    low_quantity: 2,
    category: 'Evergreen',
  },
  {
    pk: 29,
    name: 'Samsung',
    points: 950,
    display_img_url: 'https://upload.wikimedia.org/wikipedia/commons/2/24/Samsung_Logo.svg',
    quantity: 30,
    valid_until: '2026-01-10',
    low_quantity: 5,
    category: 'Evergreen',
  },
  {
    pk: 30,
    name: 'Sony',
    points: 920,
    display_img_url: 'https://upload.wikimedia.org/wikipedia/commons/2/20/Sony_Logo.svg',
    quantity: 22,
    valid_until: '2026-01-25',
    low_quantity: 5,
    category: 'Evergreen',
  },
  {
    pk: 31,
    name: 'Intel',
    points: 880,
    display_img_url: 'https://upload.wikimedia.org/wikipedia/commons/6/6a/Intel_logo_%282020%29.svg',
    quantity: 18,
    valid_until: '2026-02-05',
    low_quantity: 3,
    category: 'Evergreen',
  },
  {
    pk: 32,
    name: 'IBM',
    points: 870,
    display_img_url: 'https://upload.wikimedia.org/wikipedia/commons/5/51/IBM_logo.svg',
    quantity: 16,
    valid_until: '2026-02-15',
    low_quantity: 4,
    category: 'Evergreen',
  },
  {
    pk: 33,
    name: 'Netflix',
    points: 900,
    display_img_url: 'https://upload.wikimedia.org/wikipedia/commons/7/75/Netflix_icon.svg',
    quantity: 12,
    valid_until: '2026-03-01',
    low_quantity: 3,
    category: 'Evergreen',
  },{
    pk: 34,
    name: 'Dell',
    points: 850,
    display_img_url: 'https://upload.wikimedia.org/wikipedia/commons/4/48/Dell_Logo.svg',
    quantity: 25,
    valid_until: '2025-11-10',
    low_quantity: 5,
    category: 'Product',
  },
  {
    pk: 35,
    name: 'HP',
    points: 820,
    display_img_url: 'https://upload.wikimedia.org/wikipedia/commons/3/3a/HP_logo_2012.svg',
    quantity: 20,
    valid_until: '2025-11-25',
    low_quantity: 4,
    category: 'Product',
  },
  {
    pk: 36,
    name: 'Lenovo',
    points: 800,
    display_img_url: 'https://upload.wikimedia.org/wikipedia/commons/0/02/Lenovo_logo_2015.svg',
    quantity: 22,
    valid_until: '2025-12-05',
    low_quantity: 5,
    category: 'Product',
  },
  {
    pk: 37,
    name: 'Asus',
    points: 780,
    display_img_url: 'https://upload.wikimedia.org/wikipedia/commons/1/1e/ASUS_Logo.svg',
    quantity: 18,
    valid_until: '2025-12-15',
    low_quantity: 4,
    category: 'Product',
  },
  {
    pk: 38,
    name: 'OnePlus',
    points: 880,
    display_img_url: 'https://upload.wikimedia.org/wikipedia/commons/f/f1/OnePlus_logo.svg',
    quantity: 16,
    valid_until: '2025-12-25',
    low_quantity: 3,
    category: 'Product',
  },
  {
    pk: 39,
    name: 'Xiaomi',
    points: 770,
    display_img_url: 'https://upload.wikimedia.org/wikipedia/commons/f/f5/Xiaomi_logo_%282021-%29.svg',
    quantity: 28,
    valid_until: '2026-01-05',
    low_quantity: 6,
    category: 'Product',
  },
  {
    pk: 40,
    name: 'Vivo',
    points: 760,
    display_img_url: 'https://upload.wikimedia.org/wikipedia/commons/4/4e/Vivo_logo_2019.svg',
    quantity: 25,
    valid_until: '2026-01-15',
    low_quantity: 5,
    category: 'Product',
  },
  {
    pk: 41,
    name: 'Oppo',
    points: 750,
    display_img_url: 'https://upload.wikimedia.org/wikipedia/commons/3/3d/OPPO_logo.svg',
    quantity: 23,
    valid_until: '2026-01-25',
    low_quantity: 5,
    category: 'Product',
  },
  {
    pk: 42,
    name: 'Realme',
    points: 740,
    display_img_url: 'https://upload.wikimedia.org/wikipedia/commons/a/a2/Realme_logo.svg',
    quantity: 30,
    valid_until: '2026-02-05',
    low_quantity: 6,
    category: 'Product',
  },
  {
    pk: 43,
    name: 'LG',
    points: 810,
    display_img_url: 'https://upload.wikimedia.org/wikipedia/commons/2/20/LG_logo_%282015%29.svg',
    quantity: 26,
    valid_until: '2026-02-15',
    low_quantity: 5,
    category: 'Product',
  },
  {
    pk: 44,
    name: 'Philips',
    points: 830,
    display_img_url: 'https://upload.wikimedia.org/wikipedia/commons/1/1c/Philips_logo_new.svg',
    quantity: 20,
    valid_until: '2026-02-25',
    low_quantity: 4,
    category: 'Product',
  },
  {
    pk: 45,
    name: 'Canon',
    points: 880,
    display_img_url: 'https://upload.wikimedia.org/wikipedia/commons/7/7e/Canon_wordmark.svg',
    quantity: 12,
    valid_until: '2026-03-05',
    low_quantity: 3,
    category: 'Product',
  },
  {
    pk: 46,
    name: 'Nikon',
    points: 860,
    display_img_url: 'https://upload.wikimedia.org/wikipedia/commons/4/4e/Nikon_logo.svg',
    quantity: 14,
    valid_until: '2026-03-10',
    low_quantity: 4,
    category: 'Product',
  },
  {
    pk: 47,
    name: 'Panasonic',
    points: 790,
    display_img_url: 'https://upload.wikimedia.org/wikipedia/commons/9/9c/Panasonic_logo_%282017%29.svg',
    quantity: 18,
    valid_until: '2026-03-20',
    low_quantity: 5,
    category: 'Product',
  },
  {
    pk: 48,
    name: 'Samsung Electronics',
    points: 910,
    display_img_url: 'https://upload.wikimedia.org/wikipedia/commons/2/24/Samsung_Logo.svg',
    quantity: 22,
    valid_until: '2026-03-25',
    low_quantity: 5,
    category: 'Product',
  },
  {
    pk: 49,
    name: 'BoAt',
    points: 720,
    display_img_url: 'https://upload.wikimedia.org/wikipedia/commons/3/3b/Boat_Logo.svg',
    quantity: 24,
    valid_until: '2026-03-30',
    low_quantity: 6,
    category: 'Product',
  },
  {
    pk: 50,
    name: 'Noise',
    points: 710,
    display_img_url: 'https://upload.wikimedia.org/wikipedia/commons/f/fb/Noise_logo.svg',
    quantity: 26,
    valid_until: '2026-04-05',
    low_quantity: 5,
    category: 'Product',
  },
  {
    pk: 51,
    name: 'JBL',
    points: 880,
    display_img_url: 'https://upload.wikimedia.org/wikipedia/commons/3/3e/JBL_logo.svg',
    quantity: 20,
    valid_until: '2026-04-10',
    low_quantity: 4,
    category: 'Product',
  },
  {
    pk: 52,
    name: 'Dyson',
    points: 1150,
    display_img_url: 'https://upload.wikimedia.org/wikipedia/commons/5/52/Dyson_logo.svg',
    quantity: 10,
    valid_until: '2026-04-15',
    low_quantity: 3,
    category: 'Product',
  },
  {
    pk: 53,
    name: 'GoPro',
    points: 950,
    display_img_url: 'https://upload.wikimedia.org/wikipedia/commons/5/5d/GoPro_logo.svg',
    quantity: 15,
    valid_until: '2026-04-20',
    low_quantity: 4,
    category: 'Product',
  }
  ];

  // Generate more mock data automatically (total 50)
  

  return rewards;
  }
}